const sidebars = {
  docs: [
    'introduction',
    {
      label: 'SysAdmin Guides',
      type: 'category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sysadmin-guides'
        }
      ],
      link: {
        type: 'doc',
        id: 'guides'
      }
    }
  ]
}

module.exports = sidebars;