name: "CI - Deploy to Github Pages"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Hosted Github runners have 7GB of memory available, so lets use 6GB
  NODE_OPTIONS: --max-old-space-size=6144
  URL: https://opendocs.rootwire.co.uk
  BASEURL: /

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Build website
        run: yarn build
      - name: Set Up Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
