name: "CI - Test Deployment for Pull Requests and Pushes to main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test build website
        run: yarn build
